"""
Clinical Risk Assessment Engine
--------------------------------
Analyzes patient-reported symptoms and flags risk levels
for chronic diseases prevalent in UAE hospitals.

Target conditions: Type 2 Diabetes, Hypertension
Author: Eman Ayman AbuKhousa
Institution: IIT Guwahati — BSc Data Science & AI
Project: Clinical AI UAE
"""

DISEASE_INDICATORS = {
    "diabetes": [
        "high blood sugar", "frequent urination", "excessive thirst",
        "blurry vision", "fatigue", "unexplained weight loss",
        "slow healing wounds", "tingling in hands", "tingling in feet"
    ],
    "hypertension": [
        "severe headache", "chest pain", "dizziness",
        "shortness of breath", "nosebleed", "blurry vision",
        "fatigue", "irregular heartbeat", "pounding in chest"
    ]
}

PATIENTS = [
    {
        "id": "UAE-001",
        "name": "Ahmed Al Mansoori",
        "age": 52,
        "gender": "Male",
        "symptoms": [
            "high blood sugar", "fatigue",
            "frequent urination", "blurry vision"
        ]
    },
    {
        "id": "UAE-002",
        "name": "Fatima Al Zaabi",
        "age": 38,
        "gender": "Female",
        "symptoms": [
            "severe headache", "dizziness", "shortness of breath"
        ]
    },
    {
        "id": "UAE-003",
        "name": "Khalid Al Rashidi",
        "age": 61,
        "gender": "Male",
        "symptoms": [
            "excessive thirst", "fatigue", "blurry vision",
            "severe headache", "chest pain"
        ]
    },
    {
        "id": "UAE-004",
        "name": "Sara Al Hammadi",
        "age": 29,
        "gender": "Female",
        "symptoms": [
            "back pain", "mild headache"
        ]
    }
]


def assess_risk(symptoms: list, disease: str) -> tuple:
    """
    Assess risk level for a given disease based on symptoms.

    Args:
        symptoms: list of reported symptoms
        disease: target disease to assess

    Returns:
        tuple of (risk_level, matched_indicators)
    """
    indicators = DISEASE_INDICATORS[disease]
    matched = [s for s in symptoms if any(ind in s for ind in indicators)]
    score = len(matched)

    if score >= 3:
        level = "HIGH"
    elif score >= 1:
        level = "MODERATE"
    else:
        level = "LOW"

    return level, matched


def generate_report(patient: dict) -> dict:
    """
    Generate a full clinical risk report for a single patient.

    Args:
        patient: dictionary containing patient data

    Returns:
        dictionary containing patient info and risk assessments
    """
    report = {
        "patient_id": patient["id"],
        "name": patient["name"],
        "age": patient["age"],
        "gender": patient["gender"],
        "symptoms_reported": patient["symptoms"],
        "risk_assessment": {}
    }

    for disease in DISEASE_INDICATORS:
        level, matched = assess_risk(patient["symptoms"], disease)
        report["risk_assessment"][disease] = {
            "level": level,
            "matched_indicators": matched
        }

    return report


def print_report(report: dict):
    """
    Print a formatted clinical report to console.

    Args:
        report: dictionary generated by generate_report()
    """
    print("\n" + "─" * 50)
    print(f"  Patient ID : {report['patient_id']}")
    print(f"  Name       : {report['name']}")
    print(f"  Age        : {report['age']}  |  Gender: {report['gender']}")
    print(f"  Symptoms   : {', '.join(report['symptoms_reported'])}")
    print("  " + "─" * 46)

    for disease, result in report["risk_assessment"].items():
        level = result["level"]
        matched = result["matched_indicators"]

        flag = "⚑ " if level == "HIGH" else ("△ " if level == "MODERATE" else "  ")
        print(f"  {flag}{disease.capitalize():<16} Risk: {level}")

        if matched:
            print(f"    Indicators : {', '.join(matched)}")

    print("─" * 50)


def run_screening(patients: list):
    """
    Run full risk screening across all patients.

    Args:
        patients: list of patient dictionaries
    """
    print("\n" + "═" * 50)
    print("   CLINICAL AI — UAE PATIENT RISK SCREENING")
    print("   Conditions: Type 2 Diabetes | Hypertension")
    print("═" * 50)

    high_risk = []

    for patient in patients:
        report = generate_report(patient)
        print_report(report)

        for disease, result in report["risk_assessment"].items():
            if result["level"] == "HIGH":
                high_risk.append((patient["name"], disease))

    print(f"\n  SUMMARY — {len(patients)} patients screened")
    print(f"  High-risk flags: {len(high_risk)}")

    if high_risk:
        print("\n  Patients requiring immediate follow-up:")
        for name, disease in high_risk:
            print(f"    → {name}  ({disease.capitalize()})")

    print("\n" + "═" * 50)


if __name__ == "__main__":
    run_screening(PATIENTS)